### ISSUE TITLE
Phonon + Cordova

### ISSUE THREAD

**Issue by cedvict** [phonon-framework/phonon#251]
Hello 
Can anyone help me with use Cordova plugins like contacts or camera in Phonon project? 
Thanks

**Comment by John-Henrique** [comment]
Phonon no have dependence with Cordova or Cordova plugins, so... your problem will be with "how to use plugin...", but what is your question?

**Comment by cedvict** [comment]
Hi
I'm using phonon to make an UI of my mobile application and I want to use Cordova like a container and their plugins to interact with a native component 
but when I install Cordova plugin like contacts and I try to use like the documentation show by to writing navigator.contacts I have a mistake relative on non attribute contacts. So I want to know if phonon give a particular way to use Cordova plugins

**Comment by John-Henrique** [comment]
Phonon does not use and does not depend on any third party libraries. (by [Why use Phonon page](http://phonon.quarkdev.com/)), so you can use in your website, aplications, mobile and whetever.

Your problem is "How to use cordova plugin" and not "How to use Phonon"... Phonon no manipulate plugin methods or functions. Please, see documentation of yours plugins to see how they works.

Your problem will be solved using (from Cordova)
```
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady(){
	app.start();
}
```
See documentation of Cordova about [events](https://cordova.apache.org/docs/en/latest/cordova/events/events.html)

**Comment by qathom** [comment]
Inactive issue.
Therefore, for this reason, I close this ticket.
